### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by ghermans** [FiveM-Scripts/FiveM-Towtruck#4]
These stuff still needs to be done for the release.

- [ ]  Choose random destinations instead the current one.
- [ ] Give the player money when the job is done.
- [ ] Remove the vehicle when the job is done.
- [ ] Remove the tow truck when the job is done.
